MAINT: set/reset refered lines only when snippet window is opened
In commit 9996615, snippet window of a `CodeNodeComponent` would be
instantiated only when it is double-clicked (or clicked + KEY_ALT).

Therefore, we would get the following error:
```raw
File ".../codememo/components.py", line 1372, in reset_highlighted_lines_in_snippet
    self.node_components[idx].snippet_window.reference_info = None
AttributeError: 'NoneType' object has no attribute 'reference_info'
```

To solve this, we should check whether snippet window is None or
not before accessing it attribute `reference_info`.