TST: `AttributeError` should be caught while importing `pyglet`
`AttributeError: 'NoneType' object has no attribute '_create_shadow_window'`
will be raised first while we are trying to import `pyglet`, so that
the try-except block should also catch `AttributeError` too.