Add test for submodule `_patches` (#2)
* TST: add tests for `_patches` module

we used `pynput` to send key stroke signal to trigger key event,
but sometimes it failed to trigger callbacks defined in `PygletMixin`
(`on_key_press()` and `on_key_release()`). We still cannot figure
out the cause of it but it can be resolved by tapping those keys
listed in test case manually then rerun the test.

Besides, key press/release event sometimes will be triggered twice
on Ubuntu. After digging into the source code of `pynput`, it seems
like the redundant event is emitted as "_on_fake_event" (see also
[1]). And since we don't have enough time to gather more information
about this, we just leave it unchaged.

As for the headless rendering, passing `visible=False` to
`pyglet.window.Window` would make it not able to catch key stroke
event. Even though we have tried to run this test under a virtual
display (`xvfb`), there was still no luck. (BTW, key event will be
also triggered twice under the virtual display)

As a result of those above-mentioned reasons, we just recommand
running this test manually rather than on CI.

[1]: https://github.com/moses-palmer/pynput/blob/3bad032/lib/pynput/keyboard/_xorg.py#L266

* TST: add conftest.py to make `test__patches.py` runnable only when argument `--run_with_display` is given

Because of the restrictions mentioned in commit 4ac4816, we decided
to mark the tests in `test__patches.py` as runnable ones only when
argument `--run_with_display` is passed from CLI.

Besides, `_patches.py` is also excluded from code coverage report.

* TST: use a module level mark to skip "test__patches.py"

* TST: comment out code for adding test mark to avoid conflict

* TST: use `import pyglet` to check whether `opengl.GLU` library exists instead

* TST: move all `pyglet` related import statement into try-except block

* BUILD: add command to install requirements for test in .travis.yml

* TST: move import statements releated to `pynput` into try-except block

`pynput` requires to run with a running X server, so that it cannot
be run on a headless CI server without proper configuration.

* TST: `AttributeError` should be caught while importing `pyglet`

`AttributeError: 'NoneType' object has no attribute '_create_shadow_window'`
will be raised first while we are trying to import `pyglet`, so that
the try-except block should also catch `AttributeError` too.

* TST: revise import statement